//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace okul_yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akademisyen
    {
        public int AkdId { get; set; }
        public string AkdAd { get; set; }
        public string AkdSoyad { get; set; }
        public Nullable<int> AkdBolum { get; set; }
    }
}
